config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :place_orders
  resources :line_items
  resources :carts
  resources :users, except: [:new]
  get 'index', to: 'store#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :products do
    get :who_bought, on: :member
  end 
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-light text-black">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Gelcio Filho", "https://github.com/gelciofilho", class: "text-black" %> </small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  <% end %>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light" style= "background-color: white;">
      <%= link_to image_tag("logo.png", :alt => "Marilu T-Shirts", :class => "navbar-brand"), root_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Catalogue", index_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown active">
            <% if current_user.admin? %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin     
              </a>
            <% end %>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Manage orders", place_orders_path, class: "dropdown-item" %>
                <%= link_to "Manage Products", products_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Users", users_path, class: "dropdown-item" %> 
              </div>
            </li>
          <% end %>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Your Cart
            </a>
            <% if @cart %>
              <% if @cart.line_items.empty? %>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <p class="text-center"><%= image_tag("exclamation_mark_icon.png", class: 'cart_empty text-center bg-transparent', size:50) %><p>
                  <p class="m-1 text-info text-center">  Your cart is still empty! </p>
                  <p class="m-1 text-info text-center"> <strong> Let's start shopping? </strong> </p>
                </div> 
              <% else %>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <% if @cart %>  
                    <%= render @cart %> 
                  <% end %>
                </div> 
              <% end %>
            <% end %>
          </li>  

          <% if logged_in? %>   
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                Profile [<%= current_user.username %>] 
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'View my profile', user_path(current_user), class: "dropdown-item" %>
                <%= link_to 'Edit my profile', edit_user_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Delete profile', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
              </div>
            </li> 
            <li class="nav-item active">
              <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
            </li> 
          <% else %>
            <li class="nav-item active">
              <%= link_to "Log in", login_path, class: "nav-link" %>
            </li>  
            <li class="nav-item active">
              <%= link_to "Sign up", signup_path, class: "nav-link" %>
            </li> 
          <% end %>
                   
          
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marilu T-Shirts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>